---
# tasks file for roles/webserver

- name: install nginx
  apt:
    name: nginx
    state: present

- name: Copy File
  copy:
    src: index.html # this lookup for file in files
    dest: /var/www/html/index.html

- name: Start nginx
  service: 
    name: nginx
    state: started

- name: Configure Nginx
  template:
    src: nginx.conf.j2 # search under template folder
    dest: /etc/nginx/sites-enabled/default

  notify: restart nginx